[package]
name = "bevy_terminal_macros"
version.workspace = true
edition.workspace = true
description = "Proc-macro attributes for bevy_terminal"
repository = "https://github.com/kasper573/rift"
authors = ["kasper573"]

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
