[package]
name = "bevy_opacity"
version.workspace = true
edition.workspace = true
description = "Hierarchical opacity for bevy_ui"
repository = "https://github.com/kasper573/rift"
authors = ["kasper573"]

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_ui = { workspace = true }
bevy_text = { workspace = true }
bevy_color = { workspace = true }
bevy_time = { workspace = true }
