[package]
name = "service"
version.workspace = true
edition.workspace = true
description = "Shared conventions for rift's HTTP services"

[dependencies]
axum.workspace = true
axum-prometheus.workspace = true
tower-http = { workspace = true, features = ["normalize-path"] }
ctrlc.workspace = true
metrics-process.workspace = true
pyroscope.workspace = true
tikv-jemallocator.workspace = true
jemalloc_pprof.workspace = true
serde.workspace = true
envy.workspace = true
tokio.workspace = true
