use crate::theme::Theme;
use crate::tokens::palette;

/// Constructs the `dark` theme. Provide it to a subtree with
/// [`provide_theme`](crate::theme::provide_theme).
pub fn theme() -> Theme {
    Theme {
        scrim_light: palette::SHADE_20,
        scrim_dark: palette::SHADE_60,

        error_solid_on: palette::SLATE_100,
        error_solid_base: palette::CRIMSON_60,
        error_solid_hover: palette::CRIMSON_50,
        error_solid_active: palette::CRIMSON_40,
        error_solid_border: palette::CRIMSON_70,
        error_soft_on: palette::CRIMSON_10,
        error_soft_base: palette::CRIMSON_100,
        error_soft_border: palette::CRIMSON_10,
        error_soft_hover: palette::CRIMSON_80,
        error_soft_active: palette::CRIMSON_90,
        error_soft_on_alt: palette::CRIMSON_10,

        info_soft_on: palette::AZURE_50,
        info_soft_base: palette::AZURE_95,
        info_soft_hover: palette::AZURE_90,
        info_soft_active: palette::AZURE_80,
        info_solid_on: palette::AZURE_60,
        info_solid_base: palette::AZURE_90,
        info_solid_hover: palette::AZURE_80,
        info_solid_active: palette::AZURE_70,
        info_soft_border: palette::AZURE_30,

        primary_base: palette::AZURE_40,
        primary_hover: palette::AZURE_30,
        primary_active: palette::AZURE_20,
        primary_on: palette::SLATE_100,

        secondary_on: palette::AZURE_60,
        secondary_base: palette::AZURE_90,
        secondary_hover: palette::AZURE_80,
        secondary_active: palette::AZURE_70,
        secondary_on_alt: palette::SLATE_10,

        success_solid_base: palette::EMERALD_50,
        success_solid_hover: palette::EMERALD_60,
        success_solid_active: palette::EMERALD_70,
        success_solid_on: palette::SLATE_100,
        success_solid_border: palette::EMERALD_50,
        success_soft_on: palette::EMERALD_10,
        success_soft_base: palette::EMERALD_95,
        success_soft_border: palette::EMERALD_50,
        success_soft_hover: palette::EMERALD_90,
        success_soft_active: palette::EMERALD_80,
        success_soft_on_alt: palette::SLATE_30,

        surface_canvas_on: palette::SLATE_90,
        surface_canvas_on_soft: palette::SLATE_60,
        surface_canvas_hover: palette::SLATE_20,
        surface_canvas_active: palette::SLATE_10,
        surface_inset_on: palette::SLATE_90,
        surface_inset_on_soft: palette::SLATE_70,
        surface_inset_base: palette::SLATE_20,
        surface_inset_hover: palette::SLATE_20,
        surface_inset_active: palette::SLATE_0,
        surface_trough_on: palette::SLATE_100,
        surface_trough_on_soft: palette::SLATE_40,
        surface_trough_base: palette::SLATE_10,
        surface_trough_hover: palette::SLATE_0,
        surface_trough_active: palette::SLATE_20,
        surface_elevated_on: palette::SLATE_90,
        surface_elevated_on_soft: palette::SLATE_70,
        surface_elevated_base: palette::SLATE_40,
        surface_elevated_hover: palette::SLATE_30,
        surface_elevated_active: palette::SLATE_20,
        surface_floating_on: palette::SLATE_90,
        surface_floating_on_soft: palette::SLATE_70,
        surface_floating_base: palette::SLATE_50,
        surface_floating_hover: palette::SLATE_40,
        surface_floating_active: palette::SLATE_30,
        surface_canvas_base: palette::SLATE_30,
        surface_canvas_border: palette::SLATE_50,
        surface_inset_border: palette::SLATE_20,
        surface_trough_border: palette::SLATE_10,
        surface_elevated_border: palette::SLATE_50,
        surface_floating_border: palette::SLATE_20,
        surface_canvas_border_decorative: palette::SLATE_40,
        surface_elevated_border_decorative: palette::SLATE_50,
        surface_floating_border_decorative: palette::SLATE_10,
        surface_inset_border_decorative: palette::SLATE_20,
        surface_trough_border_decorative: palette::SLATE_10,
        surface_inverted_on: palette::SLATE_30,
        surface_inverted_base: palette::SLATE_100,
        surface_inverted_hover: palette::SLATE_95,
        surface_inverted_active: palette::SLATE_90,

        neutral_on: palette::SLATE_90,
        neutral_base: palette::SLATE_30,
        neutral_hover: palette::SLATE_20,
        neutral_active: palette::SLATE_0,
        neutral_border: palette::SLATE_50,
    }
}
