[package]
name = "world"
version.workspace = true
edition.workspace = true
description = "The game, headless and isomophic: contains no frontend and backend specific concerns"

[package.metadata.lint]
game = true

[[bin]]
name = "kc-roles"
path = "src/bin/kc_roles.rs"

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_replicon = { workspace = true, features = ["client", "server"] }
bevy_state.workspace = true
bevy_time = { workspace = true, features = ["std"] }
derive_more = { version = "2", features = ["add", "add_assign"] }
euclid = { version = "0.22", features = ["serde"] }
include_dir = "0.7"
pathfinding = "4"
renet2.workspace = true
serde.workspace = true
serde_json.workspace = true
tiled = { version = "0.15", default-features = false }
