[package]
name = "server"
version.workspace = true
edition.workspace = true
description = "Backend for the game"

[dependencies]
axum.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_replicon = { workspace = true, features = ["server"] }
renet2.workspace = true
tokio-tungstenite = { version = "0.26", default-features = false, features = ["handshake"] }
futures-util = { version = "0.3", default-features = false }
bevy_state.workspace = true
ctrlc.workspace = true
envy.workspace = true
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
metrics = "0.24"
rand = "0.9"
serde.workspace = true
serde_json.workspace = true
service = { path = "../../service" }
strum.workspace = true
tokio.workspace = true
ureq = { workspace = true, features = ["rustls", "platform-verifier"] }
world = { path = "../world" }
