apiVersion: 1

deleteDatasources:
  - name: "Mimir"
  - name: "Tempo"
  - name: "Loki"
  - name: "Pyroscope"

datasources:
  - name: "Mimir"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "$MIMIR_BASE/prometheus"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "mimir"
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: "tempo"
          name: "TraceID"

  - name: "Tempo"
    type: "tempo"
    access: "proxy"
    orgId: 1
    url: "$TEMPO_QUERY"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "tempo"
    jsonData:
      lokiSearch:
        datasourceUid: "loki"
      tracesToLogs:
        datasourceUid: "loki"
      nodeGraph:
        enabled: "true"
      serviceMap:
        datasourceUid: "mimir"
  - name: "Loki"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "$LOKI_BASE"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "loki"
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: 'traceID=(\w+)'
          name: "TraceID"
          url: "$${__value.raw}"

  - name: "Pyroscope"
    type: "grafana-pyroscope-datasource"
    access: "proxy"
    orgId: 1
    url: "$PYROSCOPE_BASE"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "pyroscope"
