[package]
name = "website"
version.workspace = true
edition.workspace = true

[dependencies]
askama.workspace = true
axum.workspace = true
axum-extra = { version = "0.10", features = ["cookie"] }
axum-prometheus.workspace = true
ctrlc.workspace = true
envy.workspace = true
metrics-process.workspace = true
openidconnect = "4"
pyroscope.workspace = true
serde.workspace = true
tokio.workspace = true
tower-http.workspace = true
